### ISSUE TITLE
O que passar na option --operacao do command completa?🤔

### ISSUE THREAD

**Issue by felipexbraga** [rjmalves/sintetizador-dessem#6]
<img width="297" alt="image" src="https://github.com/rjmalves/sintetizador-dessem/assets/101727027/d0fad19f-1bf5-4db2-9e06-671e174420a4">

Fiz alguns testes porém todos deram erro:
<img width="288" alt="image" src="https://github.com/rjmalves/sintetizador-dessem/assets/101727027/aae1cb2e-78ea-45ff-917f-14730ebc51fa">

**Comment by rjmalves** [comment]
Ei @felipexbraga . O repositório começou por agora, mas vamos melhorando a documentação aos poucos.

Nessa caso específico, você pode passar alguma palavra-chave de síntese que você deseja, por exemplo:

`sintetizador-dessem completa --operacao CMO_SBM_EST`

Esse parâmetro foi feito para você filtrar só algumas sínteses dentro da completa.

Nós vamos adicionando mais informações no site do repositório:

https://rjmalves.github.io/sintetizador-dessem/
